// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fWEp0oUuSHn4QZrleQ082g6ZsoUC-ak',
    appId: '1:592651647618:web:0e0e7828748813b521129b',
    messagingSenderId: '592651647618',
    projectId: 'daily-doer-8f65e',
    authDomain: 'daily-doer-8f65e.firebaseapp.com',
    storageBucket: 'daily-doer-8f65e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmnUc3V-CBkIzP5iLiu069ZqjVOeRUoeY',
    appId: '1:592651647618:android:1aaa42c947e82e0721129b',
    messagingSenderId: '592651647618',
    projectId: 'daily-doer-8f65e',
    storageBucket: 'daily-doer-8f65e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG68ld-JI_NLYA8pF7DTyByGJZL59C4Hs',
    appId: '1:592651647618:ios:cbe82a3675c77cdc21129b',
    messagingSenderId: '592651647618',
    projectId: 'daily-doer-8f65e',
    storageBucket: 'daily-doer-8f65e.appspot.com',
    iosClientId: '592651647618-mb9vco0hsss2djcdgvv1gh7apchbas09.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyDoer',
  );
}
